[package]
name = "therminal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3"
walkdir = "2.3"
regex = "1.5"
chrono = "0.4"

[dev-dependencies]
predicates = "2"
assert_cmd = "2"